"""empty message

Revision ID: 3cc07d71234a
Revises: 2ccdcec0fdc6
Create Date: 2021-04-22 19:22:23.951252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc07d71234a'
down_revision = '2ccdcec0fdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.PickleType(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###
