"""empty message

Revision ID: fbdd2ba47e65
Revises: 3cc07d71234a
Create Date: 2021-04-22 19:27:22.026733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdd2ba47e65'
down_revision = '3cc07d71234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows', sa.PickleType(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows')
    # ### end Alembic commands ###
